@echo off
echo Starting JSON Server...
start "JSON Server" cmd /k "npm run json-server"
timeout /t 3
echo Starting Angular Development Server...
start "Angular Server" cmd /k "npm start"
echo Both servers are starting...
pause
